DROP TABLE IF EXISTS gp20i17mp_hf.L5_TMP_DRT_BBA_META_ALL_MEASURES_BIG;
CREATE TABLE gp20i17mp_ax.L5_TMP_DRT_BBA_META_ALL_MEASURES_BIG(
  ,entity_id varchar(600)COLLATE "pg_catalog"."default",
  ,reporting varchar(600)insurance_contract_group_id varchar(600) COLLATE "pg_catalog"."default",
  ,csm_af_inv varchar(600),
  ,iacf_csm_adj varchar(600),
  ,csm_tot_adj_amt varchar(600),
  ,csm_tot_bel_adj_amt varchar(600),
  ,csm_tot_ra_adj_amt varchar(600),
  ,lc_af_inv_bel varchar(600),
  ,lc_af_inv_ra varchar(600),
  ,lc_amort_amt_bel_exp varchar(600),
  ,lc_amort_amt_ra_exp varchar(600),
  ,lc_bf_adj varchar(600),
  ,loss_declrd_bel varchar(600),
  ,loss_declrd_ra varchar(600),
  ,csm_to_lc_bel_adj_amt varchar(600),
  ,csm_to_lc_ra_adj_amt varchar(600),
  ,i17_csm_not_adj_to_rein varchar(600),
  ,i17_oci_bel_ex_chg_l_af_adj varchar(600),
  ,i17_pl_bel_ex_chg_l_af_adj varchar(600),
  ,i17_oci_ra_ex_chg_l_af_adj varchar(600),
  ,i17_pl_ra_ex_chg_l_af_adj varchar(600),
  ,i17_oci_bel_ex_chg_nl_af_adj varchar(600),
  ,i17_pl_bel_ex_chg_nl_af_adj varchar(600),
  ,i17_oci_ra_ex_chg_nl_af_adj varchar(600),
  ,i17_pl_ra_ex_chg_nl_af_adj varchar(600),
  ,i17_oci_ifie_bel_l_af_adj varchar(600),
  ,i17_pl_fin_ifie_bel_l_af_adj varchar(600),
  ,i17_oci_ifie_ra_l_af_adj varchar(600),
  ,i17_pl_fin_ifie_ra_l_af_adj varchar(600),
  ,i17_oci_ifie_bel_nl_af_adj varchar(600),
  ,i17_pl_fin_ifie_bel_nl_af_adj varchar(600),
  ,i17_oci_ifie_ra_nl_af_adj varchar(600),
  ,i17_pl_fin_ifie_ra_nl_af_adj varchar(600),
  ,lc_amort_amt_bel_adj varchar(600),
  ,lc_amort_amt_ra_adj varchar(600),
  ,lc_amort_amt_bel varchar(600),
  ,lc_amort_amt_ra varchar(600),
  ,i17_bel_if_l varchar(600),
  ,i17_ra_if_l varchar(600),
  ,i17_res_if_l varchar(600),
  ,i17_bel_if_nl varchar(600),
  ,i17_ra_if_nl varchar(600),
  ,iacf_amort varchar(600),
  ,iacf_at_e varchar(600),
  ,csm_release varchar(600),
  ,csm_if varchar(600)
WITH (APPENDONLY=TRUE, COMPRESSLEVEL=5, COMPRESSTYPE=ZLIB)
TABLESPACE  pg_default
DISTRIBUTED BY( REPORTING_DT , INSURANCE_CONTRACT_GROUP_ID );